- name: Copy python scripts
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/coursework/
    dest: /home/almalinux/coursework/
    mode: '0644'   # (read-write permissions)
    owner: almalinux
    group: almalinux

- name: Run script to create fasta file
  ansible.builtin.command:
    cmd: /home/almalinux/venv/bin/python3 /home/almalinux/coursework/subset_fasta.py /home/almalinux/coursework/experiment_ids.txt
  args:
    creates: /home/almalinux/coursework/experiment_sequences.fasta
  