- name: Copy python scripts
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/coursework/
    dest: /home/almalinux/coursework/
    mode: '0644'   # (read-write permissions)
    owner: almalinux
    group: almalinux

- name: Copy experiment sequences fasta file
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/coursework/experiment_sequences.fasta
    dest: /home/almalinux/coursework/experiment_sequences.fasta
  