- name: Install node exporter
  ansible.builtin.dnf:
    name: golang-github-prometheus-node-exporter
    state: latest
  become: true

- name: Copy service file
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/ansible/files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
  become: true

- name: Create custom metrics directory
  ansible.builtin.file:
    path: /home/almalinux/custom_metrics
    state: directory
    owner: almalinux
    group: almalinux
    mode: '0755'
  become: true

- name: Start node exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
  become: true
