- name: Install node exporter
  ansible.builtin.dnf:
    name: golang-github-prometheus-node_exporter
    state: latest
  become: true

- name: Copy service file
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/ansible/files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
  become: true
  

- name: Start node exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started
    daemon_reload: true
  become: true