- name: Install basic tools
  ansible.builtin.dnf:
    name:
      - vim
      - tmux
      - git 
      - wget
      - unzip
    state: latest
  become: true
  become_user: root

- name: Install enterprise linux
  ansible.builtin.dnf:
    name:
      - epel-release
    state: latest
  become: true
  become_user: root

- name: Copy ips file
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/ansible/ips.json
    dest: /home/almalinux/ips.json
  become: true
  become_user: almalinux