- name: Install httpd
  ansible.builtin.dnf:
    name: httpd
    state: latest
  become: true

- name: Copy index.html
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/website/index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start httpd service
  ansible.builtin.systemd:
    name: httpd
    enabled: true
    state: started
  become: true

