- name: Delete coursework directory if it exists
  ansible.builtin.file:
    path: /home/almalinux/coursework
    state: absent

- name: Delete results directory if it exists
  ansible.builtin.file:
    path: /home/almalinux/results
    state: absent