- name: Copy Celery task
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/celery/tasks.py
    dest: /home/almalinux/celery/tasks.py
  become: true

- name: Copy Celery config
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/celery/celeryconfig.py
    dest: /home/almalinux/celery/celeryconfig.py
  become: true

- name: Copy celery systemd service file
  ansible.builtin.copy:
    src: /home/almalinux/ds4eng-cw/ansible/files/celery.service
    dest: /etc/systemd/system/celery.service
  become: true

- name: Disable SELinux enforcement temporarily
  ansible.builtin.command: setenforce 0
  become: true

- name: Start celery service
  ansible.builtin.systemd:
    name: celery
    state: restarted
    daemon_reload: true
  become: true

- name: Enable SELinux enforcement again
  ansible.builtin.command: setenforce 1
  become: true