- name: Delete prometheus config if it exists
  ansible.builtin.file:
    path: /etc/prometheus/prometheus.yml
    state: absent
  become: true

- name: Stop prometheus service if running
  ansible.builtin.systemd:
    name: prometheus
    state: stopped
  become: true

