---
- hosts: all
  roles:
  - common

- hosts: host
  roles:
  - host_fasta
  - host_scripts
  - host_redis
  - host_prometheus
  - host_httpd

- hosts: workers
  roles:
  - python
  - scripts
  - hhsearch
  - s4pred
  - pdb
  - celery
  - node_exporter

