---
- hosts: all
  roles:
  - common

- hosts: host
  roles:
  - host
  - redis
  - prometheus
  - httpd

- hosts: workers
  roles:
  - python
  - scripts
  - hhsearch
  - s4pred
  - pdb
  - celery
  - node_exporter

